/**
 * One-off extraction of the existing, legally reviewed Impressum and
 * Datenschutzerklärung into structured content modules.
 *
 * The text is copied verbatim — headings and paragraphs are only re-typed as
 * data so the new design can render them. Nothing is paraphrased, shortened or
 * rewritten, because that content has been reviewed and must stay intact.
 *
 * Re-run after the source documents change:
 *   node scripts/extract-legal.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE_DIR = resolve(process.cwd(), "../web/static/landing");

function decode(value) {
  const named = {
    amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ", shy: "",
    auml: "ä", ouml: "ö", uuml: "ü", Auml: "Ä", Ouml: "Ö", Uuml: "Ü", szlig: "ß",
    eacute: "é", ndash: "–", mdash: "—", hellip: "…", bdquo: "„", ldquo: "“",
    rdquo: "”", sbquo: "‚", lsquo: "‘", rsquo: "’", euro: "€", sect: "§",
    copy: "©", reg: "®", trade: "™", deg: "°", middot: "·", bull: "•", laquo: "«", raquo: "»",
  };
  return value
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&([a-zA-Z]+);/g, (match, name) => (name in named ? named[name] : match));
}

function textOf(html) {
  return decode(
    html
      .replace(/<br\s*\/?>/gi, "\n")
      .replace(/<[^>]+>/g, "")
  )
    .replace(/[ \t ]+/g, " ")
    .replace(/\n{2,}/g, "\n")
    .trim();
}

function extract(file) {
  const raw = readFileSync(resolve(SOURCE_DIR, file), "utf8")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<!--[\s\S]*?-->/g, "");

  const body = raw.match(/<body[^>]*>([\s\S]*)<\/body>/i)?.[1] ?? raw;
  // Drop shared page chrome so only the legal document remains.
  const main = body
    .replace(/<header[\s\S]*?<\/header>/gi, "")
    .replace(/<nav[\s\S]*?<\/nav>/gi, "")
    .replace(/<footer[\s\S]*?<\/footer>/gi, "");

  const blocks = [];
  const pattern = /<(h[1-4]|p|li|td|th)\b[^>]*>([\s\S]*?)<\/\1>/gi;
  let match;
  while ((match = pattern.exec(main)) !== null) {
    const tag = match[1].toLowerCase();
    const value = textOf(match[2]);
    if (!value) continue;
    if (tag.startsWith("h")) {
      blocks.push({ type: tag === "h1" ? "title" : tag === "h2" ? "h2" : "h3", text: value });
    } else if (tag === "li") {
      const previous = blocks[blocks.length - 1];
      if (previous?.type === "list") previous.items.push(value);
      else blocks.push({ type: "list", items: [value] });
    } else {
      for (const part of value.split("\n").map((line) => line.trim()).filter(Boolean)) {
        blocks.push({ type: "p", text: part });
      }
    }
  }
  return blocks;
}

const targets = [
  { file: "impressum.html", out: "impressum" },
  { file: "datenschutz.html", out: "datenschutz" },
];

for (const target of targets) {
  const blocks = extract(target.file);
  const header =
    "// Generated by scripts/extract-legal.mjs from the reviewed source document.\n" +
    "// The wording is verbatim — do not edit here; update the source and re-run.\n" +
    'import type { LegalBlock } from "./types";\n\n' +
    `export const ${target.out}Blocks: LegalBlock[] = `;
  writeFileSync(
    resolve(process.cwd(), `src/content/legal/${target.out}.ts`),
    `${header}${JSON.stringify(blocks, null, 2)};\n`,
    "utf8"
  );
  console.log(`${target.out}: ${blocks.length} blocks`);
}
