// Generated by scripts/extract-legal.mjs from the reviewed source document.
// The wording is verbatim — do not edit here; update the source and re-run.
import type { LegalBlock } from "./types";

export const impressumBlocks: LegalBlock[] = [
  {
    "type": "title",
    "text": "Impressum"
  },
  {
    "type": "p",
    "text": "Angaben gemäß § 5 Digitale-Dienste-Gesetz (DDG)"
  },
  {
    "type": "p",
    "text": "Stand: 12. Februar 2026"
  },
  {
    "type": "h2",
    "text": "Anbieter und verantwortliche Stelle"
  },
  {
    "type": "p",
    "text": "SBS Deutschland GmbH & Co. KG"
  },
  {
    "type": "p",
    "text": "In der Dell 19"
  },
  {
    "type": "p",
    "text": "69469 Weinheim"
  },
  {
    "type": "p",
    "text": "Deutschland"
  },
  {
    "type": "p",
    "text": "Geschäftsführer: Luis Schenk"
  },
  {
    "type": "p",
    "text": "Telefon: +49 (0) 6201 24469"
  },
  {
    "type": "p",
    "text": "E-Mail: info@sbsdeutschland.com"
  },
  {
    "type": "p",
    "text": "Internet: www.sbsdeutschland.com"
  },
  {
    "type": "h2",
    "text": "Handelsregister"
  },
  {
    "type": "p",
    "text": "Registergericht: Amtsgericht Mannheim"
  },
  {
    "type": "p",
    "text": "Registernummer: HRA 706204"
  },
  {
    "type": "h2",
    "text": "Umsatzsteuer-Identifikationsnummer"
  },
  {
    "type": "p",
    "text": "Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz (UStG):"
  },
  {
    "type": "p",
    "text": "DE345927327"
  },
  {
    "type": "h2",
    "text": "Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV"
  },
  {
    "type": "p",
    "text": "Luis Schenk"
  },
  {
    "type": "p",
    "text": "In der Dell 19"
  },
  {
    "type": "p",
    "text": "69469 Weinheim"
  },
  {
    "type": "p",
    "text": "Deutschland"
  },
  {
    "type": "h2",
    "text": "Betriebene Plattformen und Dienste"
  },
  {
    "type": "p",
    "text": "Die SBS Deutschland GmbH & Co. KG betreibt folgende Online-Plattformen und SaaS-Dienste:"
  },
  {
    "type": "list",
    "items": [
      "SBS Nexus Plattform: www.sbsnexus.de — Zentrale Enterprise-Plattform",
      "SBS Deutschland Website: www.sbsdeutschland.com — Unternehmenswebsite und KI-Rechnungsverarbeitung",
      "KI-Rechnungsverarbeitung: app.sbsdeutschland.com — SaaS-Anwendung",
      "KI-Vertragsanalyse: contract.sbsdeutschland.com — SaaS-Anwendung",
      "HydraulikDoc AI: Industrielle Dokumentenanalyse und Videodiagnostik"
    ]
  },
  {
    "type": "h2",
    "text": "Hinweis zur Nutzung von Künstlicher Intelligenz"
  },
  {
    "type": "p",
    "text": "Transparenzhinweis gemäß Art. 50 Verordnung (EU) 2024/1689 (KI-Verordnung):"
  },
  {
    "type": "p",
    "text": "Die SaaS-Dienste der SBS Deutschland GmbH & Co. KG nutzen Systeme der Künstlichen Intelligenz (KI) zur Dokumentenverarbeitung, Analyse und Assistenz. KI-generierte Inhalte werden in der Benutzeroberfläche als solche gekennzeichnet. Sämtliche KI-Ergebnisse sind maschinell erzeugte Vorschläge und keine rechts-, steuer- oder fachverbindlichen Aussagen."
  },
  {
    "type": "p",
    "text": "Kundendaten werden nicht zum Training von KI-Modellen verwendet (Zero Data Retention). Weitere Informationen finden Sie in unserer Datenschutzerklärung sowie in unseren AGB (§ 12)."
  },
  {
    "type": "h2",
    "text": "Haftung für Inhalte"
  },
  {
    "type": "p",
    "text": "Als Diensteanbieter sind wir gemäß § 7 Abs. 1 DDG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 DDG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen."
  },
  {
    "type": "p",
    "text": "Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen."
  },
  {
    "type": "h2",
    "text": "Haftung für Links"
  },
  {
    "type": "p",
    "text": "Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich."
  },
  {
    "type": "p",
    "text": "Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen."
  },
  {
    "type": "h2",
    "text": "Urheberrecht"
  },
  {
    "type": "p",
    "text": "Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet."
  },
  {
    "type": "p",
    "text": "Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen."
  },
  {
    "type": "h2",
    "text": "Marken- und Kennzeichenrechte"
  },
  {
    "type": "p",
    "text": "„SBS Deutschland\", „SBS Nexus\", „HydraulikDoc AI\" und das SBS-Logo sind Marken und/oder Kennzeichen der SBS Deutschland GmbH & Co. KG. Alle anderen Marken, Produktnamen und Firmenbezeichnungen, die auf dieser Website erwähnt werden, sind Eigentum der jeweiligen Inhaber und werden lediglich zur Beschreibung oder Identifikation der entsprechenden Produkte oder Unternehmen verwendet."
  },
  {
    "type": "h2",
    "text": "EU-Streitschlichtung"
  },
  {
    "type": "p",
    "text": "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:"
  },
  {
    "type": "p",
    "text": "https://ec.europa.eu/consumers/odr/"
  },
  {
    "type": "p",
    "text": "Unsere E-Mail-Adresse finden Sie oben im Impressum."
  },
  {
    "type": "h2",
    "text": "Verbraucherstreitbeilegung / Universalschlichtungsstelle"
  },
  {
    "type": "p",
    "text": "Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen (§ 36 VSBG). Unsere SaaS-Dienste richten sich ausschließlich an Unternehmer im Sinne des § 14 BGB."
  },
  {
    "type": "h2",
    "text": "Rechtliche Dokumente"
  },
  {
    "type": "list",
    "items": [
      "Datenschutzerklärung — Informationen zum Schutz Ihrer personenbezogenen Daten gemäß DSGVO",
      "Allgemeine Geschäftsbedingungen (AGB) — Nutzungsbedingungen für alle SaaS-Dienste"
    ]
  },
  {
    "type": "p",
    "text": "Hinweis: Dieses Impressum gilt für die Internetpräsenzen sbsdeutschland.com, app.sbsdeutschland.com, contract.sbsdeutschland.com und sbsnexus.de."
  },
  {
    "type": "p",
    "text": "Rechtsgrundlage: § 5 DDG (Digitale-Dienste-Gesetz, in Kraft seit 14.05.2024, ersetzt § 5 TMG), § 18 MStV (Medienstaatsvertrag, ersetzt § 55 RStV)."
  },
  {
    "type": "p",
    "text": "Versionshistorie: v1.0 (November 2024) · v2.0 (November 2025) · v3.0 (12. Februar 2026, aktuelle Fassung)"
  }
];
